# Generated by Django 2.1.4 on 2018-12-11 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalista',
            old_name='pessoa',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 8, 36, 55, 290355, tzinfo=utc)),
        ),
    ]
