# Generated by Django 2.1 on 2018-12-07 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='mensalista',
            name='validade',
            field=models.DateField(verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 7, 10, 44, 4, 75100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='chk',
            field=models.CharField(choices=[('Não', 'CheckIn'), ('Sim', 'CheckOut')], default='Não', max_length=15, verbose_name='Situação'),
        ),
    ]
