# Generated by Django 2.1.4 on 2018-12-11 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181211_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='nome',
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 8, 37, 32, 199836, tzinfo=utc)),
        ),
    ]
