# Generated by Django 2.1 on 2018-11-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movrotativo_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='proprietario',
        ),
    ]
