# Generated by Django 2.1 on 2018-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181117_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=1212121, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
