# Generated by Django 2.1 on 2018-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181125_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='pago',
            field=models.CharField(choices=[('Não', 'Não Pago'), ('Sim', 'Pago')], max_length=15),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='pago',
            field=models.CharField(choices=[('Não', 'Não Pago'), ('Sim', 'Pago')], max_length=15),
        ),
    ]
