# Generated by Django 2.1 on 2018-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181117_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
