# Generated by Django 2.1.4 on 2018-12-11 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181211_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 8, 38, 31, 395887, tzinfo=utc)),
        ),
    ]
