# Generated by Django 2.1 on 2018-12-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_veiculo_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='email',
            field=models.ForeignKey(default=564, on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
            preserve_default=False,
        ),
    ]
