# Generated by Django 2.1.4 on 2018-12-11 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181211_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 8, 42, 43, 942971, tzinfo=utc)),
        ),
    ]
