# Generated by Django 2.1.4 on 2018-12-11 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181211_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 8, 43, 49, 72128, tzinfo=utc)),
        ),
    ]
