# Generated by Django 2.1 on 2018-12-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_mensalista_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='pessoa',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa'),
            preserve_default=False,
        ),
    ]
