# Generated by Django 2.1.2 on 2018-11-09 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movmensalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalista',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Veiculo'),
        ),
        migrations.AlterField(
            model_name='movmensalista',
            name='mensalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Mensalista'),
        ),
        migrations.AlterField(
            model_name='movrotativo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pessoa'),
        ),
    ]
