# Generated by Django 2.1 on 2018-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
