# Generated by Django 2.1 on 2018-11-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mensalista_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalista',
            name='pago',
        ),
    ]
