# Generated by Django 2.1 on 2018-11-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_mensalista_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Pessoa'),
            preserve_default=False,
        ),
    ]
