# Generated by Django 2.1 on 2018-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_contato_receber_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default=55555555, max_length=20),
            preserve_default=False,
        ),
    ]
